services:
  miner-pipeline:
    container_name: miner-pipeline
    image: miner-pipeline:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../generated_outputs:/workspace/generated_outputs
      - huggingface-cache:/root/.cache/huggingface
      - torch-cache:/root/.cache/torch
    ports:
      - "10006:10006"
    # runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - HF_HOME=/root/.cache/huggingface
      - OPENROUTER_API_KEY=placeholder

volumes:
  huggingface-cache:
    driver: local
  torch-cache:
    driver: local